#! /usr/bin/perl -w -T

package ag_postfix_mastercf;
use lib qw(.);
use strict;
use MasterCFParser;
use YaST::SCRAgent;
use ycp;
our @ISA = ("YaST::SCRAgent");

my $_CFINST = undef;

sub check_initialized ()
{
    my $class = shift;
    if (not defined $_CFINST)
    {
        $class->SetError(summary => "Agent not initialized yet",
                         code => "SCR_INIT_ERR");
    }
    return !!$_CFINST;
}

sub OtherCommand () {
    my $class = shift;
    my ($symbol, $config, @rest) = @_;
    
    if ($symbol ne "MasterCF") {
        return $class->SetError(summary=> "The first command must be the configuration.(Seen '$_')",
                                code => "SCR_INIT_ERR");
    } else {
        $_CFINST = new MasterCFParser( $config->{"path"} );
        if( not defined $_CFINST ) {
            return $class->SetError(summary => "Can not initialize MasterCFParser",
                                    code => "SCR_INIT_ERR");
        }
	# FIXME: Set logging callback here
    }
    
    return 1;
}

sub Read { 
    return 1;
}

sub Write { 
    return 1; 
}

sub Execute {
    return 1;
}
  

package main;
ag_postfix_mastercf->Run;
